/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chachachachi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;

/**
 *
 * @author dam205
 */
public final class AddEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form Horarios
     * @throws java.sql.SQLException
     * @throws java.lang.InstantiationException
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.IllegalAccessException
     */
    public AddEmpleado() throws SQLException, InstantiationException, ClassNotFoundException, IllegalAccessException {
        initComponents();
        obtenerEmpleados();
    }
    
    public Connection connection() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conexion
                = DriverManager.getConnection("jdbc:mysql://localhost/ChachaChachi",
                        "root", "");
        return conexion;
    }
    
    public void obtenerEmpleados() throws SQLException, InstantiationException, IllegalAccessException, ClassNotFoundException {
        //Creamos la conexión
        
        Connection conexion = connection();

        DefaultListModel<String> lista = new DefaultListModel<>();

        //Creamos la sentencia
        Statement sentencia = conexion.createStatement();

        //Usar la base de datos
        String usarBD = "USE ChachaChachi;";
        sentencia.executeUpdate(usarBD);
        ResultSet result = sentencia.executeQuery("SELECT e.nombre "
                + "FROM empleado e");

        while (result.next()) {
            lista.addElement(result.getString(1));
        }
        listaUsuarios.setModel(lista);
        sentencia.close();
        conexion.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(639, 447));

        lblNombre.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lblNombre.setText("Empleados");

        listaUsuarios.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listaUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lblNombre))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNombre)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
