/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chachachachi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;

/**
 *
 * @author dam205
 */
public final class AddTareas extends javax.swing.JPanel {

    /**
     * Creates new form EntradasSalidas
     * @throws java.sql.SQLException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.ClassNotFoundException
     */
    public AddTareas() throws SQLException, InstantiationException, IllegalAccessException, ClassNotFoundException {
        initComponents();
        
        obtenerTareas();
    }
     public Connection connection() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conexion
                = DriverManager.getConnection("jdbc:mysql://localhost/ChachaChachi",
                        "root", "");
        return conexion;
    }
    
    public void obtenerTareas() throws SQLException, InstantiationException, IllegalAccessException, ClassNotFoundException {
        //Creamos la conexión
        
        Connection conexion = connection();

        DefaultListModel<String> lista = new DefaultListModel<>();

        //Creamos la sentencia
        Statement sentencia = conexion.createStatement();

        //Usar la base de datos
        String usarBD = "USE ChachaChachi;";
        sentencia.executeUpdate(usarBD);
        ResultSet result = sentencia.executeQuery("SELECT e.nombre "
                + "FROM empleado e");

        while (result.next()) {
            lista.addElement(result.getString(1));
        }
        listaUsuarios.setModel(lista);
        sentencia.close();
        conexion.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        lblNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        listaUsuarios.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        listaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaUsuarios);

        lblNombre.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        lblNombre.setText("Tareas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNombre)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUsuariosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listaUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
